"""
Django settings for waseet project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os
from django.core.exceptions import ImproperlyConfigured
from dj_database_url import parse as db_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Security Settings

# Using "django-encrypted-model-fields" for email_password field encryption
# Generate Key using this command in terminal
# python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

# Python Decouple Settings:
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default=None)
# Add validation for the ENCRYPTION_KEY
if not FIELD_ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        "FIELD_ENCRYPTION_KEY must be set in environment. \n"
    )
FIELD_ENCRYPTION_KEY = FIELD_ENCRYPTION_KEY.encode()


# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure--i(h01h5=8-1)d#4@v-l!e1tl@e(n!aq9ynv4jihi^(l-x5pj_'
# Python Decouple Settings
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG Settings
# Django Default Settings
# DEBUG = True
# Python Decouple Settings
DEBUG = config('DEBUG', default=True, cast=bool)


# ALLOWED_HOSTS Settings
# Django Default Settings
# ALLOWED_HOSTS = ["alaa001.pythonanywhere.com"]
# Python Decouple Settings
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS', default='alaa001.pythonanywhere.com', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'backend',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'encrypted_model_fields',
    'model_utils',  # For Using Tracker
    'corsheaders',  # For allowing Cross-Origin Requests
    'import_export',  # django-import-export for data import/export functionality
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'waseet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'waseet.wsgi.application'


# Database
# Django Default Settings
# SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# # MySQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'waseet',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT': '3306'
#     }
# }


# Python Decouple Settings
# DATABASES = {
#     'default': config(
#         'DATABASE_URL',
#         default=BASE_DIR / 'db.sqlite3',
#         cast=db_url
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC' # Default TimeZone
TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use manage.py collectstatic to collect all static files to this folder
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework settings (Pagination)
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Firebase Configuration
FIREBASE_PROJECT_ID = 'alaa-e6e90'  # Firebase project ID
FIREBASE_CREDENTIALS_PATH = BASE_DIR / \
    'alaa-firebase-adminsdk.json'  # Path to your service account JSON


# Logging
LOG_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'notifications.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
        },
    },
    'loggers': {
        'backend.notifications': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
